export const BRAND = {
  name: "VELION MARKETS",
  shortName: "VELION",
  wordmarkSuffix: "MARKETS",
  legalEntity: "Velion Markets LLC",
  tagline: "Professional Brokerage & Wealth Management",
  domain: "velionmarkets.com",
  url: "https://velionmarkets.com",
  supportEmail: "support@velionmarkets.com",
  complianceEmail: "compliance@velionmarkets.com",
  registrationNumber: "VEL-2021-001",
  foundedYear: 2021,
  twitter: "@VelionMarkets",
  colors: {
    navy: "#09090B",
    slate: "#161616",
    gold: "#C9A227",
    emerald: "#10B981",
    emeraldSoft: "#34D399",
    emeraldGlow: "#059669",
    offWhite: "#FAFAFA",
  },
} as const;
